[package]
name = "redshift-rs"
version = "0.1.0"
authors = ["Thomas Jespersen <laumann@protonmail.com>"]

[dependencies]
time = "0.1"
chan-signal = "0.2"
chan = "0.1"
rustc-serialize = "0.3"
clap = "2"

[dependencies.xcb]
version = "0.7"
features = ["randr"]
